plugins:
  remark-preset-lint-ocular-d:
  # Customized settings
  lint-list-item-indent: space
  lint-maximum-line-length: 150
  lint-no-shell-dollars: true
  lint-no-duplicate-headings: false
  lint-maximum-heading-length: 80
  lint-heading-style: false
